---
title: "Visualization Lab 6"
author: "Roshni Sundaramurthy (rossu809) & Brian Masinde (brima748)"
date: "15 October 2018"
output:
  html_document:
    df_print: paged
  html_notebook:
    theme: journal
  pdf_document: default
fontsize: 11pt
#bibliography: references.bib
---

```{r libraries, message=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(plotly)
library(visNetwork)
library(tidyr)
library(scales)
```

## Assignment 1

### 1.1 Plot the network

```{r echo=FALSE}
df1<-read.delim("trainMeta.dat", header = T, sep='\t') #Read file

df2<-read.delim("trainData.dat", header = T, sep='\t')
```

## Assignment 2

### 2.1 Bubble chart (animated)

```{r message=FALSE, warning=FALSE}
oilcoal <- read.csv("Oilcoal.csv", sep = ";", dec = ",", header = TRUE, row.names = NULL)

oilcoal %>% plot_ly(x = ~Oil, y =~Coal, frame=~Year, text = ~Country, 
    hoverinfo = "text", type = 'scatter', mode = 'markers', size = ~Marker.size) %>%
    animation_opts(200, easing = "cubic", redraw = F) %>% add_markers(color=~Country) %>% 
    layout(title="Consumption of Oil and Coal by Countries")

```

### 2.2 Motion chart for France and Germany

```{r message=FALSE, warning=FALSE}

oilcoal %>% filter(Country==c("France","Germany"))%>%
    plot_ly(x = ~Oil, y =~Coal, frame=~Year, text = ~Country, 
    hoverinfo = "text", type = 'scatter', mode = 'markers', size = ~Marker.size) %>%
    animation_opts(200, easing = "cubic", redraw = F) %>% add_markers(color=~Country) %>% 
    layout(title="Consumption of Oil and Coal by France and Germany")

```

### 2.3 Line plot of Oilp Vs Country

```{r message=FALSE, warning=FALSE}
Oilp <- oilcoal %>% group_by(Year, Country) %>% mutate(oilp=Oil/(Oil+Coal))
Oilp_0 <- oilcoal %>% group_by(Year, Country) %>% mutate(oilp=0)
rbind(Oilp, Oilp_0) %>% 
plot_ly(x = ~oilp, y =~Country, frame=~Year, text = ~Country, 
    hoverinfo = "text", type = 'scatter', mode = 'line', size = ~Marker.size) %>%
    animation_opts(200, easing = "cubic", redraw = F) #%>% add_lines(color=~Country)

```

### 2.4 Line plot with elastic easing

```{r message=FALSE, warning=FALSE}
rbind(Oilp, Oilp_0) %>% 
plot_ly(x = ~oilp, y =~Country, frame=~Year, text = ~Country, 
    hoverinfo = "text", type = 'scatter', mode = 'line', size = ~Marker.size) %>%
    animation_opts(200, easing = "elastic", redraw = F) #%>% add_lines(color=~Country)
```

### 2.5 Guided 2D-tour visualizing coal consumption

```{r message=FALSE, warning=FALSE}
tour_df <- read.csv2("Oilcoal.csv", sep = ";")
tour_df<- tour_df[,1:5]

mat <- rescale(tour_df[,2:5])
rownames(mat) <- tour_df[,1]

set.seed(12345)
#tour <- new_tour(mat, grand_tour(), NULL)
tour<- new_tour(mat, guided_tour(cmass), NULL)

steps <- c(0, rep(1/15, 200))
Projs<-lapply(steps, function(step_size){  
  step <- tour(step_size)
  if(is.null(step)) {
    .GlobalEnv$tour<- new_tour(mat, guided_tour(cmass), NULL)
    step <- tour(step_size)
  }
  step
}
)

# projection of each observation
tour_dat <- function(i) {
  step <- Projs[[i]]
  proj <- center(mat %*% step$proj)
  data.frame(x = proj[,1], y = proj[,2], state = rownames(mat))
}

# projection of each variable's axis
proj_dat <- function(i) {
  step <- Projs[[i]]
  data.frame(
    x = step$proj[,1], y = step$proj[,2], variable = colnames(mat)
  )
}

stepz <- cumsum(steps)

# tidy version of tour data

tour_dats <- lapply(1:length(steps), tour_dat)
tour_datz <- Map(function(x, y) cbind(x, step = y), tour_dats, stepz)
tour_dat <- dplyr::bind_rows(tour_datz)

# tidy version of tour projection data
proj_dats <- lapply(1:length(steps), proj_dat)
proj_datz <- Map(function(x, y) cbind(x, step = y), proj_dats, stepz)
proj_dat <- dplyr::bind_rows(proj_datz)

ax <- list(
  title = "", showticklabels = FALSE,
  zeroline = FALSE, showgrid = FALSE,
  range = c(-1.1, 1.1)
)

# for nicely formatted slider labels
options(digits = 3)
tour_dat <- highlight_key(tour_dat, ~state, group = "A")
twoD_tour <- proj_dat %>%
  plot_ly(x = ~x, y = ~y, frame = ~step, color = I("black")) %>%
  add_segments(xend = 0, yend = 0, color = I("gray80")) %>%
  add_text(text = ~variable) %>%
  add_markers(data = tour_dat, text = ~state, ids = ~state, hoverinfo = "text") %>%
  layout(xaxis = ax, yaxis = ax)%>%animation_opts(frame=0, transition=0, redraw = F)
twoD_tour
```

